#!/usr/bin/env python


import logging
LOG = logging.getLogger("serve")
import priorityprefix

from daphne.server import Server

from app import application


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    logging.getLogger("asyncio").setLevel(logging.INFO)
    logging.getLogger("daphne.http_protocol").setLevel(logging.INFO)
    logging.getLogger("daphne.ws_protocol").setLevel(logging.INFO)
    priorityprefix.install()
    server = Server(application, endpoints=["tcp:port=8000:interface=127.0.0.1"])
    server.run()
