#!/usr/bin/env python


import logging
LOG = logging.getLogger("serve")
import priorityprefix

from uvicorn.config import Config
from uvicorn.server import Server

from app import application


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    logging.getLogger("asyncio").setLevel(logging.INFO)
    priorityprefix.install()
    config = Config(application, access_log=False)
    #for handler in logging.getLogger("uvicorn").handlers:
    #    logging.getLogger("uvicorn").removeHandler(handler)
    #logging.getLogger("uvicorn").addHandler(logging.root.handlers[0])
    logging.getLogger("uvicorn").handlers = list(logging.root.handlers)
    logging.getLogger("uvicorn.access").propagate = True
    server = Server(config=config)
    try:
        server.run()
    except KeyboardInterrupt:
        LOG.info("Interrupted - Shutting down")
