#!/usr/bin/env python


import logging
LOG = logging.getLogger("serve")
import priorityprefix

from aiohttp import web
from aiohttp_asgi import ASGIResource

from app import application


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    logging.getLogger("asyncio").setLevel(logging.INFO)
    priorityprefix.install()
    resource = ASGIResource(application)
    aiohttp_application = web.Application()
    aiohttp_application.router.register_resource(resource)
    resource.lifespan_mount(aiohttp_application)
    web.run_app(aiohttp_application, host="127.0.0.1", port=8000)
