#!/usr/bin/env python


import logging
LOG = logging.getLogger("serve")
import priorityprefix

from uvicorn.config import Config
from uvicorn.server import Server

from app import application


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    logging.getLogger("asyncio").setLevel(logging.INFO)
    priorityprefix.install()
    config = Config(application)
    server = Server(config=config)
    try:
        server.run()
    except KeyboardInterrupt:
        LOG.info("Interrupted - Shutting down")
