#!/usr/bin/env bash

# None of these seem to work properly, or at all...
#    --log-level DEBUG \
#    --log-config json:logconf.json \
#    --error-logfile "-" \
#    --access-logfile "-" \

hypercorn \
    app:application
