#!/usr/bin/env python


import logging
LOG = logging.getLogger("serve")
import priorityprefix

import asyncio

from hypercorn.config import Config
from hypercorn.asyncio import serve

from app import application


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    logging.getLogger("asyncio").setLevel(logging.INFO)
    priorityprefix.install()
    config = Config()
    asyncio.run(serve(application, config))
